name: Check Day Logic
on: [pull_request]
jobs:
  check-day:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java file
        run: javac DayCheck.java

      - name: Run day check
        run: java DayCheck